#!/usr/bin/env bash
# Install nginx

sudo apt-get update -y
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null

sudo sed -i "s#server_name _;#server_name _;\n\trewrite ^/redirect_me/$ https://www.youtube.com/watch?v=X_8Nh5XfRw0 permanent;#" /etc/nginx/sites-available/default

sudo service nginx start
