#!/usr/bin/env bash
#add header x-served-by that tells the host name that sent the response
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i "s#server_name\ _;#server_name\ _;\n\tadd_header X-Served-By \$hostname;"
sudo service nginx restart
