#!/usr/bin/env bash
#add header x-served-by that tells the host name that sent the response
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo sed -i "s#server_name\ _;#server_name\ _;\n\tadd_header X-Served-By \$HOSTNAME;\n"
sudo service nginx restart
