#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server
sudo apt-get update -y
sudo apt-get install haproxy
echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
printf %s "
frontend http_web
        bind *:80
        stats uri /haproxy?stats
        default_backend my_backend

backend my_backend
        balance roundrobin
        server 4253-web-01 54.87.26.7:80 check
        server 4253-web-02 34.227.226.141:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
