#!/usr/bin/env bash
#script that displays Best School 10 times but for the 9th iteration, displays Best School and then Hi

i=1

while [ $i -lt 11 ]
do
    echo "Best School"
    if test $i == 9
    then
        echo "Hi"
    fi
    ((i++))
done
